'''WAP that implements a "guess the number" game by generating random number'''
import random
number=random.randint(1,10)
user_input=int(input("Enter your number: "))
if user_input>number:
    print("The number you've guessed is too high")
    print("The number generated by computer was: ",number)
elif user_input<number:
    print("The number you've guessed is too low")
    print("The number generated by computer was: ",number)
else:
    print("The number generated by computer was: ",number)
    print("You've guessed the right number! Well done!!!")

    

